app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::group(array('before' => 'guest'), function(){
	
	Route::get('login', function(){
		return View::make('auth.login');
	});

	Route::post('login', 'AuthController@login');

	Route::controller('password', 'RemindersController');
});



Route::get('logout', array('before' => 'auth', 'uses' => 'AuthController@logout'));

Route::get('admin', array('before' => 'auth', function(){
	return View::make('auth.admin');	
}));


Route::group(array('before' => 'auth'), function(){

	Route::group(array('before' => 'is_admin'), function(){
		Route::resource('admin/roles', 'RolesController');
		Route::resource('admin/users', 'UsersController');
	});

	Route::resource('paises', 'PaisesController');

	Route::resource('estados', 'EstadosController');

	Route::resource('ciudades', 'CiudadesController');

	Route::resource('arbitros', 'ArbitrosController');

	Route::resource('temporadas', 'TemporadasController');

	Route::resource('torneos', 'TorneosController');

	Route::resource('estadios', 'EstadiosController');

	Route::resource('fechas', 'FechasController');
	// return JSON
	Route::get('json/fechas/torneo/{torneo_id}', 'FechasController@busquedaPorIdTorneo');

	Route::resource('posiciones', 'PosicionesController');

	Route::resource('futbolistas', 'FutbolistasController');

	Route::resource('galerias/estadios', 'GaleriasEstadiosController');

	Route::resource('clubes', 'ClubesController');
	Route::get('clubes-image/avatar/all-generate', 'ClubesController@generateAllFormatFile');

	Route::resource('categorias', 'CategoriasController');

	Route::resource('lesiones', 'LesionesController');

	Route::resource('cargos-cuerpos-tecnicos', 'CargosCuerposTecnicosController');

	Route::resource('integrantes-cuerpos-tecnicos', 'IntegrantesCuerposTecnicosController');

	Route::resource('partidos', 'PartidosController');
	// return JSON
	Route::get('json/partidos/fecha/{fecha_id}', 'PartidosController@busqueda');

	Route::resource('roles-arbitros', 'RolesArbitrosController');

	Route::resource('convocados', 'ConvocadosController');

	Route::resource('colegios', 'ColegiosController');
	
	Route::resource('goles', 'GolesController');

	Route::resource('tipo-de-gol', 'TipoDeGolController');

	Route::resource('futbolistas-amonestados', 'FutbolistasAmonestadosController');

	Route::resource('grupos', 'GruposController');

	Route::resource('estados-partidos', 'EstadosPartidosController');

	Route::resource('tiros-penales', 'TirosPenalesController');

	Route::get('en-juego/partido/{id}', 'EnJuegoController@partido');
	Route::post('en-juego/store/{id}', 'EnJuegoController@store');

	Route::get('contrato/futbolista/{id}', 'FutbolistaContratoController@create');
	Route::post('contrato/futbolista/store', 'FutbolistaContratoController@store');
	Route::post('contrato/futbolista/{id}', 'FutbolistaContratoController@update');
	Route::get('contrato/futbolista/{futbolista_id}/torneo/{torneo_id}/edit', 'FutbolistaContratoController@edit');
	// return JSON
	Route::get('contrato/torneo/{torneo_id}/club/{club_id}', 'FutbolistaContratoController@getFutbolistaByTorneoAndClub');

	Route::get('contrato/integrante-cuerpo-tecnico/{id}', 'CuerpoTecnicoContratoController@create');
	Route::post('contrato/integrante-cuerpo-tecnico/store', 'CuerpoTecnicoContratoController@store');
	Route::get('contrato/integrante-cuerpo-tecnico/{integrante_id}/torneo/{torneo_id}', 'CuerpoTecnicoContratoController@edit');

	Route::any('query/futbolistas/{query}', 'FutbolistasController@busqueda');

	// Route::post('/twitter/enviar-estado', 'TweetsController@enviarEstado');
	Route::post('tweet/partido/status', 'TweetsController@statusPartido');
	Route::post('tweet/partido/gol', 'TweetsController@gol');
	Route::post('tweet/partido/ifmt', 'TweetsController@IFMT');


	Route::get('cache/flush', function(){
		Cache::flush();
	});

});

Route::get('contacto', function(){
	return View::make('public.contacto', array('titleHeader' => 'Contacto'));
});
Route::post('contacto', 'PublicController@contacto');

Route::get('/', 'PublicController@index');

Route::get('primera-division',  'PublicController@primera');
Route::get('primera-division/fechas', 'PublicController@primeraFechas');
Route::get('primera-division/fechas/{fecha_id}', 'PublicController@primeraFecha');

Route::get('segunda-division', 'PublicController@segunda');
Route::get('segunda-division/fechas', 'PublicController@segundaFechas');
Route::get('segunda-division/fechas/{fecha_id}', 'PublicController@segundaFecha');

Route::get('tercera-division', 'PublicController@tercera');
Route::get('tercera-division/fechas', 'PublicController@terceraFechas');
Route::get('tercera-division/fechas/{fecha_id}', 'PublicController@terceraFecha');

Route::get('copa-venezuela', 'PublicController@copaFechas');
Route::get('copa-venezuela/fechas/{fecha_id}', 'PublicController@copaFecha');

app/views/galerias_de_estadios/create.blade.php
@extends('layouts.admin')

@section('main')

<h1>Create Galeria</h1>

{{ Form::open(array('route' => 'galerias.estadios.store', 'files' => TRUE)) }}
	<table>
		<tr>
            <td>{{ Form::label('imagen', 'Imagen:') }}</td>
            <td>{{ Form::file('imagen') }}</td>
        </tr>

        <tr>
            <td>{{ Form::label('estadio_id', 'Estadio_id:') }}</td>
            <td>{{ Form::select('estadio_id', $estadios, NULL, array('class' => 'form-control')) }}</td>
        </tr>

		<tr>
			<td colspan=2>
				{{ Form::submit('Submit', array('class' => 'btn btn-info')) }}
			</td>
		</tr>
	</table>
{{ Form::close() }}

@if ($errors->any())
	<ul>
		{{ implode('', $errors->all('<li class="error">:message</li>')) }}
	</ul>
@endif

@stop

app/views/galerias_de_estadios/edit.blade.php
@extends('layouts.admin')

@section('main')

<h1>Edit Galeria</h1>
{{ Form::model($galeria, array('method' => 'PATCH', 'files' => TRUE, 'route' => array('galerias.estadios.update', $galeria->id))) }}
	<img src="{{{ $galeria->imagen }}}">
	<table>
		<tr>
            <td>{{ Form::label('imagen', 'Imagen:') }}</td>
            <td>{{ Form::file('imagen') }}</td>
        </tr>

        <tr>
            <td>{{ Form::label('estadio_id', 'Estadio:') }}</td>
            <td>{{ Form::select('estadio_id', $estadios, $galeria->estadio, array('class' => 'form-control')) }}</td>
        </tr>

		<tr>
			<td>
				{{ Form::submit('Update', array('class' => 'btn btn-info')) }}
				{{ link_to_route('galerias.estadios.show', 'Cancel', $galeria->id, array('class' => 'btn')) }}
			</td>
		</tr>
	</table>
{{ Form::close() }}

@if ($errors->any())
	<ul>
		{{ implode('', $errors->all('<li class="error">:message</li>')) }}
	</ul>
@endif

@stop

app/views/galerias_de_estadios/index.blade.php
@extends('layouts.admin')

@section('main')

<h1>All Galerias</h1>

<p>{{ link_to_route('galerias.estadios.create', 'Add new galeria') }}</p>

@if ($galerias->count())
	<table class="table table-striped table-bordered">
		<thead>
			<tr>
				<th>Imagen</th>
				<th>Estadio</th>
			</tr>
		</thead>

		<tbody>
			@foreach ($galerias as $galeria)
				<tr>
					<td>
						@if(!empty($galeria->imagen))
							<img height="50" src="{{{ $galeria->imagen }}}">
						@endif
					</td>
					<td>{{{ $estadios[$galeria->estadio_id] }}}</td>
                    <td>{{ link_to_route('galerias.estadios.edit', 'Edit', array($galeria->id), array('class' => 'btn btn-info')) }}</td>
                    <td>
                        {{ Form::open(array('method' => 'DELETE', 'route' => array('galerias.estadios.destroy', $galeria->id))) }}
                            {{ Form::submit('Delete', array('class' => 'btn btn-danger')) }}
                        {{ Form::close() }}
                    </td>
				</tr>
			@endforeach
		</tbody>
	</table>
@else
	There are no galeria
@endif

@stop

app/views/galerias_de_estadios/show.blade.php
@extends('layouts.admin')

@section('main')

<h1>Show Galeria</h1>

<p>{{ link_to_route('galerias.estadios.index', 'Return to all galerias') }}</p>

<table class="table table-striped table-bordered">
	<thead>
		<tr>
			<th>Imagen</th>
			<th>Estadio</th>
		</tr>
	</thead>

	<tbody>
		<tr>
			<td>
				@if(!empty($galeria->imagen))
					<img height="50" src="{{{ $galeria->imagen }}}">
				@endif
			</td>
			<td>{{{ $estadios[$galeria->estadio_id] }}}</td>
            <td>{{ link_to_route('galerias.estadios.edit', 'Edit', array($galeria->id), array('class' => 'btn btn-info')) }}</td>
            <td>
                {{ Form::open(array('method' => 'DELETE', 'route' => array('galerias.estadios.destroy', $galeria->id))) }}
                    {{ Form::submit('Delete', array('class' => 'btn btn-danger')) }}
                {{ Form::close() }}
            </td>
		</tr>
	</tbody>
</table>

@stop